[package]
name = "derivit-core"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { workspace = true }
heck = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
darling = { workspace = true }