name: fromit

on:
  push:
    branches: [ "main" ]
    paths:
      - crates/fromit/**
  pull_request:
    branches: [ "main" ]
    paths:
      - crates/fromit/**
  

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose -p fromit
    - name: Run tests
      run: cargo test --verbose -p fromit
