name: infoit

on:
  push:
    branches: [ "main" ]
    paths:
      - crates/infoit/**
  pull_request:
    branches: [ "main" ]
    paths:
      - crates/infoit/**
  

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: crates/infoit
      run: cargo build --verbose
    - name: Run tests
      working-directory: crates/infoit
      run: cargo test --verbose
